### ISSUE TITLE
export PCA without classifier

### ISSUE THREAD

**Issue by wunderbarr** [nyoka-pmml/nyoka#10]
Hello,
I would like to ask whether it is possible to only export PCA model without classifier? 
Thank you!

**Comment by Nirmal-Neel** [comment]
Hi. Currently this functionality is not supported by Nyoka. We shall implement this in future based on our prioritized tasks. Thanks!

**Comment by nyoka-pmml** [comment]
Closing this issue for now as there is no plan to implement this feature in the near future.
