### ISSUE TITLE
Combine pipelines with mathematical expressions

### ISSUE THREAD

**Issue by mckeown12** [nyoka-pmml/nyoka#17]
I have two sklearn pipelines, both serializable via nyoka-pmml.  I would like to serialize the sum.

Similar to https://github.com/jpmml/jpmml-sklearn/issues/40 is there a way of achieving this/ supporting this with nyoka?

**Comment by nyoka-pmml** [comment]
Hi @mckeown12, currently Nyoka does not have support for this. We shall implement it based on our prioritized works.
