### ISSUE TITLE
About python Word2vec

### ISSUE THREAD

**Issue by zzf7645368** [nyoka-pmml/nyoka#20]
How to convert the Word2vec model to PMML? I don't know  how to do this, so in a sense I'm curious.  Can you help me ? Thanks!

**Comment by nyoka-pmml** [comment]
Hi @zzf7645368, word2vec is from `gensim` library and Nyoka doesn't have support for that library.

List of libraries and models supported by Nyoka is mentioned in [Supported Libraries and Models](https://github.com/nyoka-pmml/nyoka#list-of-libraries-and-models-supported-by-nyoka-)

**Comment by zzf7645368** [comment]
Thank you for your reply!  I  need to apply the  Word2vec  model on java now ,Can you give me some advice! Thanks!

**Comment by nyoka-pmml** [comment]
You can refer to https://deeplearning4j.org/docs/latest/deeplearning4j-nlp-word2vec. Thanks!

**Comment by zzf7645368** [comment]
Thanks!
