### ISSUE TITLE
ArimaToPMML error

### ISSUE THREAD

**Issue by rcprati** [nyoka-pmml/nyoka#21]
Hi, 

I have tried the ArimaToPMML function, and I got an error "AttributeError: 'DataFrame' object has no attribute '_index'".

I have changed line 157 in arima.py, changing "_index" to "index", and this seems to fix the problem. I am not sure this is an issue with some pandas version or a bug.

**Comment by Nirmal-Neel** [comment]
Hi @rcprati , thanks for pointing this out. In the current implementation, Nyoka expects a Pandas series to be fitted to the model. But yes, the input data could be DataFrame also.

In the next release of Nyoka, we will consider this.

**Comment by nyoka-pmml** [comment]
Hi @rcprati , this issue is resolved in [Nyoka 4.0.1](https://github.com/nyoka-pmml/nyoka/releases/tag/4.0.1)
