### ISSUE TITLE
keras to pmml result pmml xml file not support by jpmml

### ISSUE THREAD

**Issue by ebullientfly** [nyoka-pmml/nyoka#23]
After use keras to pmml, I get the result pmml xml file. But when I use jpmml to load pmml file, it report that elment "DeepNetwork" not support by PMML-4_4

**Comment by Nirmal-Neel** [comment]
Hi @ebullientfly , DeepNetwork is not part of PMML 4.4. This is something that will be available from PMML 5.0 probably.

**Comment by Nirmal-Neel** [comment]
Since your question is answered, I am closing this issue.

**Comment by tarilabs** [comment]
Hi @Nirmal-Neel could you kindly explain more about it, please?
I have similar problem, I have a keras model, and then I do per manual:

```
pmmlObj=KerasToPmml(model)
pmmlObj.export(open('model.pmml','w'),0)
```

for which I obtain the below PMML, which however does not execute for the same reason.

How can I execute the keras model in PMML, or from Java alternative which would support the execution, please?

Thanks!

```
<?xml version="1.0" encoding="UTF-8"?>
<PMML xmlns="http://www.dmg.org/PMML-4_4" version="4.4">
    <Header copyright="Copyright (c) 2018 Software AG" description="Keras Model in PMML">
        <Application name="Nyoka" version="4.2.1"/>
        <Timestamp>2020-07-17 19:09:47.629324</Timestamp>
    </Header>
    <DataDictionary numberOfFields="2">
        <DataField name="input" optype="categorical" dataType="string"/>
        <DataField name="predictions" optype="continuous" dataType="double"/>
    </DataDictionary>
    <DeepNetwork functionName="regression" numberOfLayers="50">
        <MiningSchema>
            <MiningField name="input" usageType="active" invalidValueTreatment="asIs"/>
            <MiningField name="predictions" usageType="target" invalidValueTreatment="asIs"/>
        </MiningSchema>
        <Output>
            <OutputField name="predicted_predictions" optype="continuous" dataType="double" feature="predictedValue"/>
        </Output>
        <NetworkLayer layerType="Input" layerId="signal" connectionLayerId="na" inputFieldName="input">
            <LayerParameters inputDimension="(4096, 12)" outputDimension="(4096, 12)"/>
        </NetworkLayer>
...
```

**Comment by Nirmal-Neel** [comment]
Hi @tarilabs, the schema that Nyoka uses is a superset of the official PMML 4.4 schema. This extended schema contains definitions for DeepNetwork which is not official. DeepNetwork will be made official as part of PMML 5.0 schema which may or may not have the same definitions. Nyoka has a transitive relationship with a proprietary tool (both products are developed under same organisation) which can understand/execute DeepNetwork models.

I hope this answers your question.
