### ISSUE TITLE
StackingClassifier

### ISSUE THREAD

**Issue by krovyakov12** [nyoka-pmml/nyoka#24]
Hello!

When I try convert model on the base of sklearn.ensemble.StackingClassifier to pmml get following:

NotImplementedError: StackingClassifier is not Implemented!

**Comment by Nirmal-Neel** [comment]
Hi @krovyakov12 , Nyoka does not support StackingClassifer. So the error is NotImplementedError.

**Comment by krovyakov12** [comment]
Thanks for answer.

Do you plan to support it in near future? 
Or it's impossible?

**Comment by Nirmal-Neel** [comment]
It is quite possible. But there are some high priority tasks in the pipeline. Will consider it in future releases.
