### ISSUE TITLE
how to reload the pmml file?

### ISSUE THREAD

**Issue by moseshu** [nyoka-pmml/nyoka#25]
Hello!
      I save the Keras model as pmml file . but how to reload it by nyoka API?
my code is 

   pmml = KerasToPmml(keras_model=model, model_name="text", predictedClasses=[1, 0])
   pmml.export(open("%s/model/cnn.pmml" % path, "w"), 0)
I use the model  to predict the binary text classification, the parameter predictedClasses is right to be given?

**Comment by Nirmal-Neel** [comment]
Yes. You are using the exporter in correct way. However, Nyoka is an exporter only. It only allows you to convert a model into PMML.

**Comment by moseshu** [comment]
> Yes. You are using the exporter in correct way. However, Nyoka is an exporter only. It only allows you to convert a model into PMML.

I get i ！tthank you
