### ISSUE TITLE
which python package can load pmml file?

### ISSUE THREAD

**Issue by moseshu** [nyoka-pmml/nyoka#26]
Hello! I  exstract a pmml file like this
pmml = KerasToPmml(keras_model=grid, model_name="text", predictedClasses=[1, 0]) pmml.export(open("%s/model/cnn.pmml" % path, "w"), 0)

but when I load the pmml file by pypmml:
model = pypmml.Model.fromfile(name = "%s/model/cnn.pmml" % path)
data=[3] * 100
df = pd.DataFrame([data])
model.predict(df)
it gave me below:
Empty DataFrame
Columns: []
Index: []
 how can I load the pmml file to predict the data?

**Comment by Nirmal-Neel** [comment]
Hi @moseshu, I am not sure how pypmml works. But the point is that DeepNetwork is not part of PMML 4.4 schema. Please verify whether pypmml has support for this.
