### ISSUE TITLE
How to convert a trained XGBoost model file into PMML

### ISSUE THREAD

**Issue by weiguoz** [nyoka-pmml/nyoka#33]
For example, I have already trained the model with the following code snippet.
How to convert such `my_model` into a PMML formatted model?
``` Python
# ...
bst = xgbost.train(param, dtrain, num_round)
bst.save_model("my_model")
```

**Comment by Nirmal-Neel** [comment]
Hi @weiguoz, Nyoka only supports XGBClassifier and XGBRegressor class. See the [XGBoost Examples](https://github.com/nyoka-pmml/nyoka/blob/master/examples/xgboost/1_xgboost.ipynb)
