### ISSUE TITLE
DecisionTreeRegressor exports as classification

### ISSUE THREAD

**Issue by VaradDaniel** [nyoka-pmml/nyoka#37]
When exporting a SKL DecisionTreeRegressor model on a continuous target, the pmml file shows 

functionName="classification" 
<DataField name="target" optype="categorical"> in both DataDictionary and MiningSchema

and <OutputField name="probability_None" optype="continuous" dataType="double" feature="probability" value="None"/>
            <OutputField name="predicted_target" optype="categorical" feature="predictedValue"/>

**Comment by Nirmal-Neel** [comment]
Hi @VaradDaniel, which version of scikit-learn are you using? Nyoka works fine till version 0.20.4. We will release a new version of Nyoka with support for latest version of scikit-learn.

**Comment by VaradDaniel** [comment]
HI Nirmal, using scikit-learn 0.23.1.. let me try downgrading and to 0.20.4 and check

**Comment by VaradDaniel** [comment]
ok, so can confirm that the issue goes away when you downgrade scikit-learn.
