### ISSUE TITLE
Support for Regression Neural Networks

### ISSUE THREAD

**Issue by hancelpv** [nyoka-pmml/nyoka#5]
Hello, 

Currently, I see that nyoka can only handle CNNs (MobileNet), which is also given in the example. 
Can nyoka support other kind of Neural Networks, specifically the ones used for regression ?

**Comment by sharmasw** [comment]
Hi, Yes Nyoka does support DNN based models for regression. We will add a few examples of regression problems in the example section. 

For now, below is an example:

import keras
from keras.models import Sequential
from keras.layers import *
import sys
from nyoka import KerasToPmml

model = Sequential()
model.add(Dense(13, input_dim=13, kernel_initializer='normal', activation='relu'))
model.add(Dense(23))
model.add(Dense(1, kernel_initializer='normal'))
# Compile model
model.compile(loss='mean_squared_error', optimizer='adam')

pmmlObj=KerasToPmml(model)
pmmlObj.export(open('RegPMML.pmml','w'),0)

Thanks!

**Comment by OpusTen** [comment]
Thank you so much for your prompt reply ! But my issue, is not resolved yet.
I'm attaching my reproducible code and the pmml output file here.
**PMML file still shows the attributes of MobileNet model.**
Kindly run it and check. Thanks.


import keras
from keras.models import Sequential
from keras.layers import *
import sys
from nyoka import KerasToPmml

data = pd.DataFrame(boston.data)
features = list(boston.feature_names)
target = 'PRICE'
data.columns = features
data['PRICE'] = boston.target

x_train, x_test, y_train, y_test = train_test_split(data[features], data[target], test_size=0.20, random_state=42)


model = Sequential()
model.add(Dense(13, input_dim=13, kernel_initializer='normal', activation='relu'))
model.add(Dense(23))
model.add(Dense(1, kernel_initializer='normal'))

model.summary()
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(x_train, y_train, epochs=1000, verbose=0)

model_name = 'Keras_Neural_Net'

model_save_dir = '../Results/'
model_file_path = model_save_dir + str(model_name) + '.pmml'

pmmlObj=KerasToPmml(model)
pmmlObj.export(open(model_file_path,'w'),0)

**Comment by sharmasw** [comment]
Could you please share your PMML file.  There might be some version issue.

**Comment by OpusTen** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<PMML xmlns="http://www.dmg.org/PMML-4_3" version="4.3Ext">
    <Header copyright="Internal User, exported to PMML by Nyoka (c) 2019 Software AG" description="Keras Models in PMML">
        <Timestamp>2019-01-11 15:12:40.263731</Timestamp>
    </Header>
    <DataDictionary numberOfFields="2">
        <DataField name="image" optype="categorical" dataType="binary" mimeType="image/png">
            <Extension extender="ADAPA" name="BINARY_BUFFERED" value="true"/>
        </DataField>
        <DataField name="predictions" optype="categorical" dataType="string"/>
    </DataDictionary>
    <DeepNetwork modelName="MobileNet" functionName="classification" numberOfLayers="4">
        <MiningSchema>
            <MiningField name="image" usageType="active" invalidValueTreatment="asIs"/>
            <MiningField name="predictions" usageType="predicted" invalidValueTreatment="asIs"/>
        </MiningSchema>
        <Output>
            <OutputField name="predictedValue_predictions" optype="categorical" dataType="string" feature="predictedValue"/>
            <OutputField name="top1_prob" dataType="double" feature="probability"/>
            <OutputField name="top5_prob" optype="categorical" dataType="string" feature="topCategories" numTopCategories="5"/>
        </Output>
        <LocalTransformations>
            <DerivedField name="base64String" optype="categorical" dataType="string" trainingBackend="tensorflowChannelLast" architectureName="MobileNet">
                <Apply function="CNN:getBase64String">
                    <FieldRef field="image"/>
                </Apply>
            </DerivedField>
        </LocalTransformations>
        <NetworkLayer layerType="Input" layerId="dense_1_input" connectionLayerId="na" inputFieldName="base64String">
            <LayerParameters inputDimension="(13,)" outputDimension="(13,)"/>
        </NetworkLayer>
        <NetworkLayer layerType="Dense" layerId="dense_1" connectionLayerId="dense_1_input">
            <LayerParameters activationFunction="rectifier" inputDimension="(13, 1)" outputDimension="(13, 1)"/>
            <LayerWeights weightsShape="(13, 13)" weightsFlattenAxis="0">
				data:float32;base64,23AtvpNkBr5w76U9OAsyvNSFC7uilhi95AjiPeL/TT6Ao+w7sDQQvBvjjr2Oioi+bHQtvVaONLtPV2S95FC4vM9iQb3zbUq99vJTOziigj5jxjw6I09YPI3M37xpToa8ShPEvU8ApDxn+9a7GDVbveWXfL0fW228pJ2DvUbM270IeKM+vm0YPYzQhb2LY269sJj9POUruz2Dv428cDKHPsfqiT7rDWs+Z3MuvMgJkryOjhs/CKwOPfdosL7Phvy87YLgPH/tG72hS9y9w94fvdMdQb4G1M+9zjHLvFlBCjwS4AG+ZmA0vnGulr6wuds9cLHNvDy1Pb0QJfM8sWWpPBBPbr1q0YM/HqBHPxceyD+zISi64h0APQG+PD/6arE+vMWNv9n/KjxupUC9clNgPI9oDb8TyIs9afdevesad73EQSq8IwpgvJtrPDx2ZN688+ddPnLvDT19/1u8Z1abvdu84rtcByC+SE92vWgAQr16re693kWQvis1lDwiHm87+nZav+1rK7/keuY9OA3KO2phBr0QxRQ8PknPPhdMxrxjDms9a3YTPfWciz3tPis8H2ervcJBlT78wRa+AjuxvQBkQ72auwq8r5MUvB3J3z7slKA89Jh3PMGJjzywaYO8v15Au5dzgLvuVdA8aQuUPG0LMT1cc7a8uYcLPMPJRr3tAp29FXhhvaCVmLoGBNq9D83fvnp5tjww8Qu9fLXOvglyCL6Besk9X98GvSzm4jzy1Pe82JgUPpJ1Jr09FaA99WLsO5QvpTxdGmq9n6QGvENofDwA5Gi9znr5u2IHdb24i5G964icPEpnbT0qtWk8HTjQvQqZH77SXZO+mcJkvZ2ilb2MOJq/klcpv2VYQzxbLk698W4FvWSsjrumII29GI2rPQ==
            </LayerWeights>
            <LayerBias biasShape="(13, 1)" biasFlattenAxis="0">
				data:float32;base64,apoOP4BO3T7FhGY+b8jEu992HbzvToI9jEDjPvm9Cb8AAAAATUOWvAAAAAD8Wla9AAAAAA==
            </LayerBias>
        </NetworkLayer>
        <NetworkLayer layerType="Dense" layerId="dense_2" connectionLayerId="dense_1">
            <LayerParameters activationFunction="linear" inputDimension="(13, 1)" outputDimension="(23, 1)"/>
            <LayerWeights weightsShape="(13, 23)" weightsFlattenAxis="0">
				data:float32;base64,yyx5vlEEkzy/wru+RHeEvgVx/Lympes9BpJ+PVpFkb6jW7W9GkisvtDcdr3J7KO+IM9kvtkanD7zK7S+zmxUPkHbc73a8H0+sPWMvuJsvj5hRy0+Zi9/voMczLmauJW8ujWnvmuyt73rQ+W9+TmoPsC86r0Unw4+pdXDvsyndDzYWUO+UKSDPtr4QD5NfQw9fSk7vrBxqL46DkG97BuqPiqWQL4xP7E+EbA2PvlMkr3fk4i9meGCPc6OgL+434Q/iTKavuYux77xDTA/qwg/P8/zTT+ipiW/s4gRv52kH79pEiE+paFvv3sne7+KSH8//31JvtAxCz9ciAU/JIsjP8/2Zj+yq1Q+2qYLPx2YEL9dtAc/TvZyPgT8rL7ofBW+srbAPp+Zmj49bMG9CCqcPibQdD65Cm++IDHsvYXsIT5db9O7x/iUvlNVSz5INGm9YWKpvqzJz74N1yw8milJvoIN5b33NU6+2Jw0vr+o3j0Ha7480hOPvSa0xT5VVlW++uXHvhQXvj7qRMe+MSkMvmnkKz6lPZ2+LcAnviMjhT1t5a8+0h6MvlXuSTw61+K9vfIwvgC0UL0/lFi9SIr5Owgb3L3A+8i+hsfBPjXY0L4ENgY/QjawvjJ0D7/o+EY+dKX9vfBJyj6YAJq+Z4a9Pgwu/b4jy0C9R00vPrWSEz41CY0+MLKavtrXjL7eeAs/0H3+Ph3+Dz4v4T8/nl9dP+Lw5j5XeOM92CPsvgSwzT4Lbje+bZaVvl06073eZjW+uii+PSZSrr4DY0k+v0KTPbmDqz6e9w+/a49ZvjJe6T5P9bS+zm0NvmibrD69OB8+EwmsPu7m7j6cUPY+zsVHvhejAj+AOpq9QeSDuWEdu7ybsUO+DJvcvV0nBb4jxZu+2Tc/Ph9ulTx1y1Q9df2NvTL8bD4ksae9qbhjvsY7V7wtgJ6+eca+vqEzUbtVVbK9NxnAvnTIgb7+zbA+aiMxvkzRMj6aMq0+OuR6vugsTb2wASo+ANdZPsChTT4w8LA8qA25PpCVVj5MvKI+Ah3KvmgRXD4ABhM+QDrHvH4Hxz68uLS93vsSvkReoT6wbuo9yLMQPnrXqT6wjr092myau3zBDTzhgr++7TCmviEMTj4s/oe+H2lBPoVyqj5jYLI+hHLyvBWVlT4h9vC9NSqYvnxDnb5wZac+GKbIvrMlrL4Asoi+p46MvuhLHz58mMm+EvEEPnSPNT7Ykak+sGtJvYAOYr4kxoU+rB71vXWSUr4AqKg+dA2CPhjYt73Y8G4+4G4kPOwZjj65E7u+6JDFPTyusD1FunS+pkqHvrjOVb62Xqq+zAmyPszyZj64+Dg+jPeqvi3ZVb4zA4S9BdqrPVFUMz6ITm28RQufvniYk75c3MQ+K32mPvpICj4AzA8+rMbKPlAbtj6LE4m+M8oSPcB7wj5LKSc+vuzhvm34O75w4yG/E4tQv6n4ML2pC9u+4PCYPoRbRT64Uri+E5Y6vkLzoz4gDvQ9RAXjvfajbr5Op8m++tbCPugiJr1Y78s+QDXovFg7i70UyrQ++JUavaCj9j3k0Zu98Nh1vlieiz6MIKG90M+0vd46qz4=
            </LayerWeights>
            <LayerBias biasShape="(23, 1)" biasFlattenAxis="0">
				data:float32;base64,FyUIv3uvFT9bI/q+BOACvxck7z405es+desHPzWG+L6Ofrq+SD8Kvxm60z7ingK/9FsAv17ZDz+VnfW+PkPTPlMJCD+eofU+NGETP1h4Dz+JFiI/GPCPvUSy9j4=
            </LayerBias>
        </NetworkLayer>
        <NetworkLayer layerType="Dense" layerId="dense_3" connectionLayerId="dense_2">
            <LayerParameters activationFunction="linear" inputDimension="(23, 1)" outputDimension="(1, 1)"/>
            <LayerWeights weightsShape="(23, 1)" weightsFlattenAxis="0">
				data:float32;base64,5cs9vvt8nT7cy729erPDvUyRuj3gB4Q+KqprPvMtTr5sTh2+gRXYveP45TrXoCG+EQJHvmW3fT5474G9qk3wPYDukD1UXYE+rpVTPp6azz0Cb9M+WBcIvYE/qj0=
            </LayerWeights>
            <LayerBias biasShape="(1, 1)" biasFlattenAxis="0">
				data:float32;base64,fXXkPg==
            </LayerBias>
        </NetworkLayer>
    </DeepNetwork>
</PMML>

**Comment by OpusTen** [comment]
I'm not able to send the file, since the PMML format is not supported for attachments here.

**Comment by sharmasw** [comment]
Could you please install the nyoka from GitHub once, might be the issue is with the version of Nyoka installed.
If the problem still persists, I will push a new updated version, and that will solve the problem for sure.

**Comment by OpusTen** [comment]
I git cloned the repository, installed the package using the command 'python setup.py install' and re ran the code.
Still, the issue persists. Kindly push an updated version, if you think that'll solve the issue.
Thanks a lot !

**Comment by Nirmal-Neel** [comment]
Hi @hancelpv. Support for Sequential model is added with [Nyoka Build 2.0.0](https://github.com/nyoka-pmml/nyoka/releases/tag/2.0.0). Please try with the latest build. Also available in PyPI.

Find the example notebook [here](https://github.com/nyoka-pmml/nyoka/blob/master/examples/keras/2_PMML_generation_for_Sequential_Model.ipynb).
Thanks!
