### ISSUE TITLE
Version 3.5 comes with undocumented dependencies

### ISSUE THREAD

**Issue by alex23lemm** [nyoka-pmml/nyoka#8]
Hi all, 

Today I set up my standard conda environment from scratch I use for exporting DNN architectures to PMML with the latest version 3.5 of Nyoka (`pip install nyoka`). Unfortunately, Nyoka seems to come with new undocumented dependencies after having added support for exporting time series models in version 3.5 which was not the case for the previous versions.

While trying to execute the statement `from nyoka import KerasToPMML` the following errors occurred:

### issue 1: pandas missing

![Image 3](https://user-images.githubusercontent.com/611112/55016375-e9830780-4fee-11e9-824b-94fc7ed9a57c.png)

Even though I just wanted to use `KerasToPMML`, `ArimaToPMML` forced me to install pandas. 

### issue 2: statsmodels.tsa missing

![Image 4](https://user-images.githubusercontent.com/611112/55016502-2cdd7600-4fef-11e9-8975-14e3255c046b.png)
 
After installing statsmodels I was able to import KerasToPMML as originally intended. 

You can easily reproduce this issue while setting up a fresh conda env using the following script and executing the import statement from above in a Juypter notebook:

```
conda create --name testDL python
activate testDL

conda install ipython
conda install jupyter
conda install scipy
conda install requests
conda install lxml

pip install --ignore-installed --upgrade tensorflow
pip install --upgrade keras

pip install nyoka
```
Best, 
Alex

**Comment by Nirmal-Neel** [comment]
Hi @alex23lemm , this issue is resolved in [Nyoka Build 3.0.7](https://github.com/nyoka-pmml/nyoka/releases/tag/3.0.7).

The same is also uploaded to PyPi.
